language: bash

env:
  global:
  - secure: UrIeCrbVNx+IIDJ9KUNvhvbUrbK26K06Dlk1lhIc3NSr+pHIy6j9ovOL2DhZQA4Wt9jRHc0acnnPhdvuVT3MHeQyb5gqYaH3+rGy9rGjJ0RXCfwHE4OVpdWZcLB650iu99JmU0+T1Y2Ov5TL+IFT8S3Hc+so3QOyHPnq9dozoK6GgpYAqt0q4ozQbPMlGEHUo4CrY5FzBrYiVRFGDKt2QMRQmvZnFakeIRS/XMjOYSegq9T3HwKQOc5I+YnYAjR2lIVbtLBDWeMU2TClvqS3Sklv9qD8DB5cCtjfB9AcZbAP7kb57Xr0wpdy/2UvUQwW9cpfK2EHxpDrUp6IleTxkXi6uxk9lmQEgHc4t05ZzDh/OICPS31vOIs6vIVXB/XmzGh7vOcjTcmQ/fztbMw2eDN7hil8Ol6nBcvmcUXyKqHlfKAiqwHeve9jybQG6DG6tmYxn1DKJBGgSg8jJ7ruxB8wD9kzm5Xf5lJp4j+V0Qal4DtxgQxbiLdKUk7OT0xdUlxMgVFSwGN7snMsINP7UlHgBQ46xsFAUZQnKKUa3IDCmVViGB25cg+hwqAnLuQ7vNSg41uVBu0ZPJTOl9Hu4+bNkgBqmKo6Blmc0JI/8dswgx3hKzCo1DHaNOrcAtqZF2vFs0U/AlyzWt+fgax8oFO8OOelf58T08h41w6gy4o=
  - secure: nbBGdzazHkTyKFrV+A2LXrQmhOGgA0h4daOFqLtju4itCqIRRw2ALXG6IAKezaidR1GMMLUi8MaLzzJt2LVC92poalw0wrCkXYTLsIAt0WwQP/t/NOrYSlHNRyxfahxzILsb3t79LIQdcOsb6bfHqyFDXR2Z27k/6mp42oLtV5zKJSRChkY4kThYafjVFOVMVUzrOW1qJKdFBXABNnPs1QkVI490jr2lGzbbd04DAGlYl08MBw8z3uczkyetXG3jJ9ZsljrbebTcsFBxeYT7E9AgRj5cmvIkuJKPF5PaPP8UlotOPXCjZwtCHkTsmMPfM8MD4EDJO2htHEjUH2/cZLJBo1rGKsLLEJEK472SOgpSuHm24bKviT1Atmu8f67ZuWwpHU/onPW7uaAb+D21DeeVQVh4m/H3b7SHGDDqmqaXrmmoCeI8DnkxF5IF98SiMG59RBODXTXqYCDPlw0g9adYyH+wUfQC94yjZpH5NDHyQjJyRsqz5tqAzt5uXwDUYiIaO4wPCBp4Pjr9fbrnxWiskrvp3mtxn2c3UM2KqBmQhEgtNVPncXS4r8SoKh3UfH5dwUCbV2oX9Cn90T4bPz5QpkXKHFTeZm0E6Pk/UT+hLTkc60Biweb39VxicSrIfPHLENp51XTzoNL1Vegijl0f4wOU6xCfdWObU4vGGs4=

services:
- docker

before_install:
- docker image build --tag nogayama/myapp1:latest .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image push nogayama/myapp1:latest

script:
- echo hello
