language: bash

env:
  global:
  - secure: nbBGdzazHkTyKFrV+A2LXrQmhOGgA0h4daOFqLtju4itCqIRRw2ALXG6IAKezaidR1GMMLUi8MaLzzJt2LVC92poalw0wrCkXYTLsIAt0WwQP/t/NOrYSlHNRyxfahxzILsb3t79LIQdcOsb6bfHqyFDXR2Z27k/6mp42oLtV5zKJSRChkY4kThYafjVFOVMVUzrOW1qJKdFBXABNnPs1QkVI490jr2lGzbbd04DAGlYl08MBw8z3uczkyetXG3jJ9ZsljrbebTcsFBxeYT7E9AgRj5cmvIkuJKPF5PaPP8UlotOPXCjZwtCHkTsmMPfM8MD4EDJO2htHEjUH2/cZLJBo1rGKsLLEJEK472SOgpSuHm24bKviT1Atmu8f67ZuWwpHU/onPW7uaAb+D21DeeVQVh4m/H3b7SHGDDqmqaXrmmoCeI8DnkxF5IF98SiMG59RBODXTXqYCDPlw0g9adYyH+wUfQC94yjZpH5NDHyQjJyRsqz5tqAzt5uXwDUYiIaO4wPCBp4Pjr9fbrnxWiskrvp3mtxn2c3UM2KqBmQhEgtNVPncXS4r8SoKh3UfH5dwUCbV2oX9Cn90T4bPz5QpkXKHFTeZm0E6Pk/UT+hLTkc60Biweb39VxicSrIfPHLENp51XTzoNL1Vegijl0f4wOU6xCfdWObU4vGGs4=
  - DOCKER_USER: nogayama

services:
- docker

before_install:
- docker image build --tag nogayama/myapp1:latest .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
- docker image push nogayama/myapp1:latest

script:
- echo hello

